[theme]
base="light"
primaryColor="#0A3D91"                 # Nexa Blue
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F8FB"     # light slate
textColor="#0F172A"                     # near-black slate
font="sans serif"
