[theme]
primaryColor = "#1E3A8A"              # Nexa Blue
backgroundColor = "#FFFFFF"           # Page background
secondaryBackgroundColor = "#FFF9E6"  # Cards/sidebar (soft gold)
textColor = "#0F172A"                 # Near-black text
font = "sans serif"
