# === Messaging ===
TWILIO_ACCOUNT_SID = ""
TWILIO_AUTH_TOKEN  = ""
TWILIO_FROM        = "+15550000000"

SENDGRID_API_KEY   = ""
SENDGRID_FROM      = "noreply@nexa.example"

# === Database (Postgres recommended; falls back to SQLite if blank) ===
DATABASE_URL = ""   # Example: "postgresql+psycopg2://user:pass@host:5432/nexa"

# === App ===
DEFAULT_TIMEZONE   = "America/New_York"
